In [28]:
import numpy as np
filepath='/home/huanglong/tensorflow/Machine-learning-in-action-master/k-Nearest Neighbor/datingTestSet2.txt'

ValueError: I/O operation on closed file

In [26]:
import cv2

In [24]:
print returnMat

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
returnVect = np.zeros((1,24))
returnVect[0,4]=3 #表示第0行第四个
print returnVect

[[0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [70]:
import numpy as np
a=np.random.randint(0,3,20).reshape(5,4)
b=np.random.randint(0,3,8).reshape(2,4)

In [71]:
print a,b

[[1 0 2 0]
 [0 1 0 0]
 [2 2 1 2]
 [0 1 2 1]
 [1 2 2 2]] [[1 0 1 1]
 [0 2 2 2]]


In [78]:
diffMat = np.tile(a, (b.shape[0],1))
print diffMat

[[1 0 2 0]
 [0 1 0 0]
 [2 2 1 2]
 [0 1 2 1]
 [1 2 2 2]
 [1 0 2 0]
 [0 1 0 0]
 [2 2 1 2]
 [0 1 2 1]
 [1 2 2 2]]


In [77]:
print diffMat-b

ValueError: operands could not be broadcast together with shapes (10,4) (2,4) 